version: 2 # Do not upgrade to 2.1 until CircleCI CLI supports it

jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
        environment:
          CI: true
    steps:
      - checkout
      - run:
          name: Install node packages
          command: npm ci
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test --verbose --logHeapUsage --maxWorkers=2
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results
      - run:
          name: Publish coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -f test-results/coverage/coverage-final.json
      - run:
          name: Release to npm (only on master)
          command: npm run release

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
