version: 2 # Do not upgrade to 2.1 until CircleCI CLI supports it

jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          name: Restore downloaded packages from cache
          key: yarn-dependency-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          name: Save downloaded packages to cache
          key: yarn-dependency-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
      - run: yarn test --verbose
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results
      - run:
          name: Publish coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -f test-results/coverage/coverage-final.json
      - run: yarn release # Will only release to NPM on master branch

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
