version: 1
update_configs:
  - directory: /
    package_manager: javascript
    update_schedule: weekly
    commit_message:
      prefix: chore
    default_reviewers:
      - paulgain
      - rafenden
      - yeahfro
